// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NorthWind.Sales.Backend.DataContexts.EFCore.DataContexts;

#nullable disable

namespace NorthWind.Sales.Backend.DataContexts.EFCore.Migrations
{
    [DbContext(typeof(NorthWindContext))]
    partial class NorthWindContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NorthWind.Sales.Backend.BusinessObjects.POCOEntities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength();

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<int>("DiscountType")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipAddress")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ShipCity")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ShipCountry")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ShipPostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ShippingType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NorthWind.Sales.Backend.Repositories.Entities.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength();

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("City")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("ProfilePictureContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("ProfilePictureData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = "ALFKI",
                            Cedula = "0102030405",
                            City = "Berlin",
                            CurrentBalance = 0m,
                            Email = "alfreds@mail.com",
                            FirstName = "Alfreds",
                            LastName = "Futterkiste",
                            PasswordHash = "AQAAAAIAAYagAAAAEKz3F1o5Z2tVhZ4kF0K1V2K1V2K1V2K1V2K1V2K1V2K1V2K1V2K1V2K1",
                            Phone = "+49-30-007-1234",
                            SecurityStamp = "ALFKISTAMP"
                        },
                        new
                        {
                            Id = "ANATR",
                            Cedula = "0203040506",
                            City = "México D.F.",
                            CurrentBalance = 0m,
                            Email = "ana@mail.com",
                            FirstName = "Ana",
                            LastName = "Trujillo",
                            PasswordHash = "AQAAAAIAAYagAAAAEKz3F1o5Z2tVhZ4kF0K1V2K1V2K1V2K1V2K1V2K1V2K1V2K1V2K1V2K1",
                            Phone = "+52-55-1234-5678",
                            SecurityStamp = "ANATRSTAMP"
                        },
                        new
                        {
                            Id = "ANTON",
                            Cedula = "0304050607",
                            City = "México D.F.",
                            CurrentBalance = 100m,
                            Email = "antonio@mail.com",
                            FirstName = "Antonio",
                            LastName = "Moreno",
                            PasswordHash = "AQAAAAIAAYagAAAAEKz3F1o5Z2tVhZ4kF0K1V2K1V2K1V2K1V2K1V2K1V2K1V2K1V2K1V2K1",
                            Phone = "+52-55-8765-4321",
                            SecurityStamp = "ANTONSTAMP"
                        });
                });

            modelBuilder.Entity("NorthWind.Sales.Backend.Repositories.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("NorthWind.Sales.Backend.Repositories.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<short>("UnitsInStock")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chai",
                            UnitPrice = 35m,
                            UnitsInStock = (short)20
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chang",
                            UnitPrice = 55m,
                            UnitsInStock = (short)0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aniseed Syrup",
                            UnitPrice = 65m,
                            UnitsInStock = (short)20
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chef Anton's Cajun Seasoning",
                            UnitPrice = 75m,
                            UnitsInStock = (short)40
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chef Anton's Gumbo Mix",
                            UnitPrice = 50m,
                            UnitsInStock = (short)20
                        });
                });

            modelBuilder.Entity("NorthWind.Sales.Backend.BusinessObjects.POCOEntities.Order", b =>
                {
                    b.HasOne("NorthWind.Sales.Backend.Repositories.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NorthWind.Sales.Backend.Repositories.Entities.OrderDetail", b =>
                {
                    b.HasOne("NorthWind.Sales.Backend.BusinessObjects.POCOEntities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NorthWind.Sales.Backend.Repositories.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
